spring:
  r2dbc:
    url: r2dbc:postgresql://${SERVER}:${PORT}/${DB_NAME}?schema=${SCHEMA}
    username: ${USERNAME}
    password: ${PASSWORD}
    pool:
      enabled: true
  graphql:
    graphiql:
      enabled: true